-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE merchants (
    uuid text PRIMARY KEY,
    name text NOT NULL,
    address_1 text NOT NULL,
    address_2 text,
    address_city text NOT NULL,
    address_state text,
    address_zipcode text NOT NULL,
    address_country text NOT NULL,
    primary_email text NOT NULL UNIQUE,
    primary_phone text NOT NULL,
    auth_code text NOT NULL,
    access_id text NOT NULL,
    access_key text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX merchants_pkey ON merchants(uuid text_ops);
CREATE UNIQUE INDEX merchants_primary_email_key ON merchants(primary_email text_ops);
